eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    forward-headers-strategy: framework
spring:
    application:
        name: springGatewayServer
    cloud:
        config:
            uri: http://localhost:8888
        gateway:
            default-filters:
                    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: databaseservice
                predicates:
                - Path=/databaseservice
                uri: lb://databaseservice
            -   id: administrationservice
                predicates:
                - Path=/administrationservice
                uri: lb://administrationservice
            -   id: educationservice
                predicates:
                - Path=/educationservice
                uri: lb://educationservice
            -   id: notificationservice
                predicates:
                - Path=/notificationservice
                uri: lb://notificationservice
            -   id: keycloakadminserver
                predicates:
                - Path=/keycloakadminserver
                uri: lb://keycloakadminserver


#    main:
#        allow-bean-definition-overriding: true
#    security:
#        oauth2:
#            client:
#                provider:
#                    keycloak:
#                        issuer-uri: http://localhost:8555/auth/realms/Adminication
#                registration:
#                    springGatewayServer:
#                        authorization-grant-type: authorization_code
#                        client-id: springGatewayServer
#                        client-secret: d97d98cb-0ec3-4212-b1a5-834c5a766887
#                        provider: keycloak
#                        scope: openid,profile,email,offline_access
