eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    forward-headers-strategy: framework
spring:
    application:
        name: springGatewayServer
    cloud:
        config:
            uri: http://localhost:8888
        gateway:
            default-filters:
                    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin TokenRelay
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
            -   id: databaseservice
                predicates:
                - Path=/databaseservice
                uri: lb://databaseservice
            -   id: administrationservice
                predicates:
                - Path=/administrationservice
                uri: lb://administrationservice
            -   id: educationservice
                predicates:
                - Path=/educationservice
                uri: lb://educationservice
            -   id: notificationservice
                predicates:
                - Path=/notificationservice
                uri: lb://notificationservice
            -   id: keycloakadminserver
                predicates:
                - Path=/keycloakadminserver
                uri: lb://keycloakadminserver

    main:
        web-application-type: reactive

        allow-bean-definition-overriding: true