eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
spring:
    application:
        name: educationService
    cloud:
        config:
            uri: http://localhost:8888
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8555/auth/realms/Adminication/protocol/openid-connect/certs